# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
#google-ID: 'UA-112060364-1'

menu:
- {name: 'About Me', path: 'menu', url: 'about'}
#- {name: 'Writing', path: 'menu', url: 'writing'}
- {name: 'Services', path: 'menu', url: 'services'}
- {name: 'Projects', path: 'menu', url: 'projects'}
- {name: 'Ideas', path: 'menu', url: 'ideas'}
- {name: 'Curriculum Vitae', path: 'menu', url: 'files/joshua-rogers-security-engineer.pdf'}
- {name: 'Contact', path: 'menu', url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - icon: 'github'
    link: 'https://github.com/MegaManSec'
    label: 'GitHub'

  - icon: 'x-twitter'
    link: 'https://x.com/MegaManSec'
    label: 'X (Twitter)'

  - icon: 'linkedin'
    link: 'https://www.linkedin.com/in/joshua-alexander-rogers/'
    label: 'LinkedIn'

  - icon: 'hackernews'
    link: 'https://news.ycombinator.com/user?id=mmsc'
    label: 'Hacker News'

  - icon: 'rss-square'
    link: '/feed.xml'
    label: 'RSS Feed'

#  - icon: 'envelope'
#    link: 'mailto:contact@joshua.hu'
#    label: 'Mail'

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

#sharing_button_prompt: 'Feel free to share!'

#related_posts: 'You may also enjoy:'

post_date_prefix: 'Published on'
use_related_posts: true
